pipeline {
    agent {
        docker "node:alpine"
    }

    stages {
        stage("Build") {
            steps {
                dir("frontend") {
                    sh "npm install"
                    sh "npm run build"
                }
            }
        }
    }
}