pipeline {
    agent {
        docker "node:alpine"
    }

    node {
        stages {
            stage("Build") {
                steps {
                    dir("frontend")
                    sh "npm install"
                    sh "npm run build"
                }
            }
        }
    }
}
