pipeline {
    agent any

    stages {
        stage("Build backend docker image") {
            steps {
                dir("backend") {
                    withDockerRegistry({url: "", credentialsId: "docker-hub-dentych") {
                        script {
                            def img = docker.build("dinnerdash/backend")
                            img.push()
                        }
                    }
                }
            }
        }
    }
}
