pipeline {
    agent any

    stages {
        stage("Build backend docker image") {
            steps {
                dir("backend") {
                    script {
                        docker.withRegistry("", "docker-hub-dentych")
                        def img = docker.build("dinnerdash/backend")
                        img.push()
                    }
                }
            }
        }
    }
}
